# Generated by Django 4.1.2 on 2022-11-30 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_created=True, verbose_name='Дата редактирования')),
                ('destination', models.SmallIntegerField(verbose_name='Кому(поле id)')),
                ('status', models.CharField(choices=[('1', 'Вакансия'), ('2', 'Резюме')], default=None, max_length=50, verbose_name='Заявка на что')),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-data_created'],
            },
        ),
    ]
