# Generated by Django 4.1.2 on 2022-10-22 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_work', models.IntegerField(verbose_name='Стаж работы')),
                ('salary', models.IntegerField(verbose_name='Желаемая заработная плата')),
                ('about_me', models.TextField(max_length=500, verbose_name='О сотруднике')),
                ('status', models.CharField(choices=[('T_W', 'TO_WORK'), ('N_P', 'NOT_PUBLISHED'), ('Y_P', 'YES_PUBLISHED')], default='T_W', max_length=3)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор вакансии')),
            ],
        ),
    ]
