# Generated by Django 4.1.2 on 2022-10-24 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-data_updated'], 'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AddField(
            model_name='resume',
            name='data_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='about_me',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='О сотруднике'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='exp_work',
            field=models.IntegerField(default=0, verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Желаемая заработная плата'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('T_W', 'В работе'), ('N_P', 'Не опубликовано'), ('Y_P', 'Опубликовано')], default='T_W', max_length=3, verbose_name='Статус резюме:'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор резюме'),
        ),
    ]
