# Generated by Django 4.1.2 on 2022-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_resume_options_resume_data_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл с резюме'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
