# Generated by Django 4.1.2 on 2022-10-25 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_user_department'),
        ('back', '0003_resume_file_alter_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='data_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='exp_work',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.PositiveIntegerField(default=0, verbose_name='Желаемая заработная плата'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название вакансии')),
                ('description', models.TextField(max_length=500, verbose_name='Описание вакансии')),
                ('exp_work', models.PositiveSmallIntegerField(default=0, verbose_name='Требуемый стаж работы')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Заработная плата')),
                ('status', models.CharField(choices=[('T_W', 'В работе'), ('N_P', 'Не опубликовано'), ('Y_P', 'Опубликовано')], default='T_W', max_length=3, verbose_name='Статус резюме:')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования/публикации')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounts.department', verbose_name='Департамент')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор вакансии')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-data_updated'],
            },
        ),
    ]
