# Generated by Django 4.1.2 on 2022-10-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_resume_data_updated_alter_resume_exp_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание вакансии'),
        ),
    ]
