# Generated by Django 4.1.2 on 2022-10-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_vacancy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Департамент'),
        ),
    ]
