# Generated by Django 4.1.2 on 2022-10-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_department'),
        ('back', '0006_alter_vacancy_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounts.department', verbose_name='Департамент'),
        ),
    ]
