# Generated by Django 4.1.2 on 2022-11-01 11:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_alter_vacancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about_me',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True, verbose_name='О сотруднике'),
        ),
    ]
