# Generated by Django 4.1.2 on 2022-11-01 11:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_alter_resume_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about_me',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='<p>Условия:</p><ul><li></li><li></li></ul>', max_length=500, verbose_name='О сотруднике'),
        ),
    ]
