# Generated by Django 4.1.2 on 2022-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_alter_resume_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about_me',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='О сотруднике'),
        ),
    ]
